### PR TITLE
💄 widen quicksearch box wider so ‘h’ in "Quick Search" isn’t cut off

### PR DESCRIPTION
**Pull request by cheapsteak**
image

### CODE REVIEW

**Comment by alex-wilmer** [comment]
👍

**Comment by shanewilson** [comment]
can you make it bigger? wider and taller? just so the text doesn't look so squished?

**Comment by cheapsteak** [comment]
@shanewilson how's this?
image

**Comment by alex-wilmer** [comment]
@shanewilson can we merge this? do you have a totally different vision?

**Comment by shanewilson** [comment]
I have a totally different vision for quick search in general but this is good until we address that ticket

**Comment by alex-wilmer** [comment]
thanks, cc @cheapsteak

**Pull request merged**
