### PR TITLE
🐛 [PRTL-1169] sort most frequent mutations table and chart

### PR DESCRIPTION
**Pull request by Jephuff**
requires https://github.com/NCI-GDC/gdcapi/pull/793

### CODE REVIEW

**Comment by Jephuff** [comment]
Note: holding off until relay modern update.

**Comment by shanewilson** [comment]
does this actually fix the issue or not yet?

**Comment by Jephuff** [comment]
It does not, hoping relay modern will fix it :D

**Comment by shanewilson** [comment]
```
remove `relay.forceFetch();` and `.sort((a, b) => b.score - a.score)` from `FrequentMutationsTable.js`
go to `/exploration?searchTableTab=mutations`
select a project id facet
click clear button
the table will no longer be in order (should be sorted on `# Affected Cases in Cohort`) (edited)
```

**Comment by Jephuff** [comment]
This is ready for review again @NCI-GDC/oicrdevs

**Pull request merged**
