### PR TITLE
🐛PRTL-1173 add "Available Variation Data is SSM" to filters

### PR DESCRIPTION
**Pull request by cheapsteak**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
can you add this to https://github.com/NCI-GDC/portal-ui/pull/1634 please?

**Comment by alex-wilmer** [comment]
or point it to there and merge it

**Comment by cheapsteak** [comment]
Base changed to explore-link-fixes

**Comment by cheapsteak** [comment]
uh oh, diff increased

**Comment by cheapsteak** [comment]
Cherry picked commit and made separate PR here
https://github.com/NCI-GDC/portal-ui/pull/1639

**Comment by cheapsteak** [comment]
should i close this?

**Comment by cheapsteak** [comment]
or change base back to enable-cohort-links and merge this in too?

**Pull request closed without merging**
