### PR TITLE
mutation page, cancer distribution and consquences

### PR DESCRIPTION
**Pull request by cy**
screen shot 2016-10-31 at 3 05 41 pm

### CODE REVIEW

**Comment by cy** [comment]
screen shot 2016-10-31 at 5 28 06 pm

**Comment by shanewilson** [comment]
is this just waiting for review?

**Comment by cy** [comment]
yes - and better icon for consequence

**Comment by cy** [comment]
- put gene name in the 1st col
- double check 0496ee87-764c-543e-975f-f34a9a2e2bd9 coding dna change
- transcript list: vertical list
-change id in chart subtitle to 'this mutation'

**Comment by cy** [comment]
screen shot 2016-11-01 at 8 22 06 pm
done! r? @NCI-GDC/oicrdevs

**Comment by junjun-zhang** [comment]
That's cool, you made an impressive minus sign, 💯 

A missense consequence type would be even better, it would show the actual aa change in the second column

**Comment by cy** [comment]
@junjun-zhang screen shot 2016-11-01 at 10 30 27 pm

**Pull request merged**
