### PR TITLE
feat(autocomplete): PRTL-123 close the dropdown

### PR DESCRIPTION
**Pull request by ithinkicancode**
Closes #PRTL-123

### CODE REVIEW

**Comment by cy** [comment]
White space changes except https://github.com/NCI-GDC/portal-ui/pull/1027/files#diff-ee483b9b4d5de3d7a7924e8d3a84f45bR8? When I click on an item in the dropdown, it just closes the dropdown without adding to the textbox though.

**Comment by ithinkicancode** [comment]
@cy, thanks. Apparently, a `blur` event occurs before a `click` event. Commenting out `$scope.onBlur = blur;` restores the `click` event. Might have to live with this. `$scope.onBlur = blur;` only serves the purpose of dismissing the dropdown when you tab away. Clicking away is already handled by `$scope.$on('application:click', blur);`

**Comment by cy** [comment]
👍

**Comment by ithinkicancode** [comment]
As @cy mentioned, the only change (other than the white space removal) is line #577: https://github.com/NCI-GDC/portal-ui/pull/1027/files#diff-5f713a963cb0793aa8d40dd725dbbf24R577

**Comment by cy** [comment]
previous attempt caused https://jira.opensciencedatacloud.org/browse/PRTL-183, added listeners for click outside and keydown 'esc'

**Comment by alex-wilmer** [comment]
looks good! 👍

**Pull request merged**
