### PR TITLE
✏️ PRTL-1353, PRTL-1354 use gene+aachange instead of mutation id for survival legend， Sort facet buckets by doc_count desc

### PR DESCRIPTION
**Pull request by cheapsteak**
image

Test Instructions:
Open this page
http://deploybot.gdc.cheapsteak.net:32845/exploration?facetTab=mutations&searchTableTab=mutations

And verify that facet buckets are sorted by descending order, and clicking on a Survival Analysis button would result in the overall survival plot showing a legend with the Gene Symbol + AA Change

### CODE REVIEW

**Comment by cheapsteak** [comment]
Just the on in the mutations tab

**Comment by cheapsteak** [comment]
Oh nvm looks like it changes on project page as well

**Comment by shanewilson** [comment]
also survival plots needs to be updated - basically we can't show mutation uuids in any graph

**Comment by Jephuff** [comment]
That should be all of the mutation ones, the others use gene symbol

**Pull request merged**
