### PR TITLE
:bug: [PRTL-745] Case table - # Files is incorrect

### PR DESCRIPTION
**Pull request by SidSyrus**
Added missing data category.

### CODE REVIEW

**Comment by shanewilson** [comment]
case has a `file_count` directly under summary - can we use this number for the file count column?

**Comment by SidSyrus** [comment]
Oh! Ok I will use that then. Would you still like to have that category added to the mapping?

**Comment by shanewilson** [comment]
we can - not sure it matters though since I don't think we show that column on the UI do we?

**Comment by SidSyrus** [comment]
Not that I know of.

**Pull request merged**
