### PR TITLE
🐛 [PRTL-788] link to repo page from projects files column

### PR DESCRIPTION
**Pull request by Jephuff**

### CODE REVIEW

**Comment by shanewilson** [comment]
where are all these truncating requests coming from.

**Comment by Jephuff** [comment]
https://jira.opensciencedatacloud.org/browse/PRTL-789
It's also whats on prod

**Comment by shanewilson** [comment]
just have the text wrap don't ellipse

**Comment by Jephuff** [comment]
👍  sure

**Pull request merged**
