### PR TITLE
🐛💄 PRTL-1087 Firefox: Fix OncoGrid fullscreen view

### PR DESCRIPTION
**Pull request by cheapsteak**

### CODE REVIEW

**Comment by Jephuff** [comment]
Background is still black in my firefox :( 
image

**Comment by cheapsteak** [comment]
Weird
It's showing up as white on mine (black at first then flickers to white)

**Comment by Jephuff** [comment]
ahh, the one in explore worked for me, but the one on the project page didn't.

**Comment by cheapsteak** [comment]
I see, it seems like the fullscreen styles weren't being applied when going full screen from the projects page...

moved the background color to the container instead (assumption being it'll always be in a container that has a white bg)

**Comment by cheapsteak** [comment]
updated, could you take another look when the build'd done tomorrow?

**Pull request merged**
