### PR TITLE
✨ [PRTL-420] update download permission check for files with no projects

### PR DESCRIPTION
**Pull request by cy**
ticket says all `Data Type = Copy Number QA Metrics` files will have no projects associated, check file state and file acl instead. There doesn't seem to be any files of that type indexed currently, so wrote some tests.

### CODE REVIEW

**Comment by cy** [comment]
btw re-install node_modules to get the new tests to run because babel-jest was added

**Comment by Jephuff** [comment]
The logic here looks good to me. Is there a way I can test this? I don't have any projects :(

**Comment by cy** [comment]
@Jephuff no projects? 😢 Ask @Fgerthoffert to email dbGap?

**Comment by Jephuff** [comment]
for the slash on GDC_AUTH could you use `url-join` instead? It will make it a bit more resilient :)

**Comment by cy** [comment]
@Jephuff reseting the GDC_AUTH slash change because you've fixed it in a different pr

**Comment by shanewilson** [comment]
this also seems important - is it ready to merge?

**Comment by cy** [comment]
@shanewilson yup, just tested it again. Should be good.

**Pull request merged**
