### PR TITLE
✨ PRTL-1024 PRTL-1031 Add quicksearch to home page 

### PR DESCRIPTION
**Pull request by cheapsteak**
Uses namespacing solution found by Jeff and discussed here https://github.com/acdlite/recompose/issues/358

### CODE REVIEW

**Comment by cheapsteak** [comment]
@alex-wilmer could you take a look? I think you'll like it :)

**Comment by alex-wilmer** [comment]
Interesting. was the namespacing required to make something work? looks like you're just destructuring the stuff you had just previously namespaced anyways. it's a good idea to avoid collisions though definitely. 

lgtm besides missing type definition `TSearchHit`

**Comment by cheapsteak** [comment]
Preventative measure, especially for props like `state`, `setState`, and `reset`

**Comment by cheapsteak** [comment]
@alex-wilmer TSearchHit type imported :)

**Comment by alex-wilmer** [comment]
Did you push? I don't see any changes

**Comment by cheapsteak** [comment]
my bad, pushed to the wrong branch, should be there now

**Pull request merged**
