### PR TITLE
✨ [PRTL-1068] annotation cell in gene summary

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by Jephuff** [comment]
Wanna add PRTL-1069 into this PR, very related :)

**Comment by alex-wilmer** [comment]
That adds a link to the cohort page, so I wasn't going to put these together.

**Comment by Jephuff** [comment]
right! once this is merged then I'll rebase explore :D

**Comment by alex-wilmer** [comment]
explore's pretty far out. was wondering if it was worth rebasing it or trying to cherry pick the useful bits

**Pull request merged**
