### PR TITLE
🔧 vscode autoFixOnSave

### PR DESCRIPTION
**Pull request by cheapsteak**
Will save me from having to stash and reapply this over and over

### CODE REVIEW

**Comment by Jephuff** [comment]
I have no problems with this :D @shanewilson I think is the only other vscode user?

**Comment by shanewilson** [comment]
sure although I think you should add the flow stuff too:

```
    "flow.stopFlowOnExit": true,
    "flow.enabled": true,
    "flow.useNPMPackagedFlow": true,
    "flow.showStatus": true,
    "flow.runOnEdit": true,
```

**Comment by cheapsteak** [comment]
added flow stuff

**Comment by cheapsteak** [comment]
anything blocking this ? @shanewilson @Jephuff

**Pull request merged**
