### PR TITLE
feat(header): PRTL-119 notifications from endpoint

### PR DESCRIPTION
**Pull request by cy**
screen shot 2016-09-14 at 12 54 15 pm

### CODE REVIEW

**Comment by cy** [comment]
- smaller icon
- red - match legacy
- yellow - orange in barchart

**Comment by cy** [comment]
screen shot 2016-09-21 at 4 08 01 pm
^@phuongmy

**Comment by shanewilson** [comment]
I think the notifications that can't be dismissed should always be at the top

**Comment by cy** [comment]
now sorted by dismissible

**Comment by cy** [comment]
hang on, need to push the content down when banners are up

**Comment by cy** [comment]
ok pushed down

**Comment by seancannata** [comment]
@cy This can get merged when you are available. ✅

**Pull request merged**
