### PR TITLE
⬆️ npm install with npm 5.4

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by Jephuff** [comment]
Shouldn't this be into next?

**Comment by alex-wilmer** [comment]
Yes & I need to downgrade my atom packages as to not have prettier mess up this code or:

No & do it here and merge this into next since we'll need it there anyways

--- 

can be done in either order

**Comment by Jephuff** [comment]
hmm, concerned with running lint on master, could cause some real issues when rebasing next. next also seems to not have any changes when running `npm i`? could we hold off until next is merged into master?

**Comment by alex-wilmer** [comment]
sure

**Comment by Jephuff** [comment]
Or just drop the `eslint --fix` commit, package-lock.json conflicts are easy enough to resolve :)

**Comment by alex-wilmer** [comment]
but then travis fails on a zillion eslint errors. I'll just rollback my editor

**Comment by alex-wilmer** [comment]
https://github.com/NCI-GDC/portal-ui/pull/2127

**Pull request closed without merging**
