### PR TITLE
✏️ [PRTL-1838] update demo queries

### PR DESCRIPTION
**Pull request by alex-wilmer**
so I'm pretty sure this code fixes the issue, but it looks like the set ids which are used in the demo have been pre made with the wrong filters.

### CODE REVIEW

**Comment by cy** [comment]
I might be wrong, is https://github.com/NCI-GDC/portal-ui/blob/d585048899510c22e6e89a4fff503215b17a929d/src/packages/%40ncigdc/components/analysis/Demo.js#L26 supposed to create the set with the filters from availableAnalysis?

**Comment by cy** [comment]
https://github.com/NCI-GDC/portal-ui/pull/2201/files#diff-33895a36722d8309c36e182dca686c4bR64 the filter changed, should update the set name to `Bladder, High Impact, Mutect2` to match

**Comment by alex-wilmer** [comment]
updated

**Comment by alex-wilmer** [comment]
hmm I do on netlify but not locally. looking into it

**Comment by alex-wilmer** [comment]
fixed. we weren't passing `filters` along when you click the demo button

**Pull request merged**
