### PR TITLE
✨ [PRTL-1610] popup with link to manage sets on success save

### PR DESCRIPTION
**Pull request by Jephuff**
The bug where the first notification doesn't display is unrelated to this and fixed in https://github.com/NCI-GDC/portal-ui/pull/2061

### CODE REVIEW

**Comment by cy** [comment]
Didn't notice you wanted to merge into my branch; kept changing it - now there's conflicts could you rebase 😅

**Comment by Jephuff** [comment]
no worries, it's a small change :D

**Comment by cy** [comment]
after going to the manage sets page, can't close the notification plus it doesn't timeout hmm

**Comment by Jephuff** [comment]
hmmm, that shouldn't happen. I rebased and tested and it seems to be working. Would you mind testing one more time? hopefully it was just a weird merge conflict :)

**Comment by Jephuff** [comment]
@cy I think I've fixed it now. thanks!

**Pull request merged**
