### PR TITLE
✨ SparkMeter in ssmsTable

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by shanewilson** [comment]
does this need to be added to more tables? did we have that bar chart on any entity pages?

**Comment by alex-wilmer** [comment]
it could be added to the genes table, but we're keeping that bar chart afaik

**Comment by shanewilson** [comment]
just the bar charts that have mutations id on the x axis need to be removed

**Comment by alex-wilmer** [comment]
right, so this good then, yes?

**Pull request merged**
