### PR TITLE
💄 flexwrap pie charts

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
image

**Comment by Jephuff** [comment]
Might be better to left align, this looks a bit strange
image

File tab will need an update as well, it probably should hide pie charts when there are spaces available (probably also needs 'space-between')
image

**Comment by alex-wilmer** [comment]
I don't know, I think its worth getting in now. Simple fix for:

image

@Jephuff not sure I feel that left aligned is better than centered in this case

**Comment by shanewilson** [comment]
the `show more` thing in jeffery's screenshot doesn't really make sense anymore.

**Comment by alex-wilmer** [comment]
doesn't it? that adds more pies.

**Comment by alex-wilmer** [comment]
in any case, this pr doesn't impact that

**Comment by shanewilson** [comment]
why don't the pies just fill in the empty space? It looks weird

**Comment by Jephuff** [comment]
Maybe instead of wrapping, extra pies should be hidden? based on the file tab it seems the motivation was to keep it 1 row.

**Comment by alex-wilmer** [comment]
I don't care I just want it to not break

**Comment by shanewilson** [comment]
hiding extra pies is fine but falls under features vs bug fix

**Pull request merged**
