### PR TITLE
PRTL-1562 add 'distinct (unique)' to CancerDist mutation tooltip

### PR DESCRIPTION
**Pull request by cy**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
why do we need both distinct and unique?

**Comment by alex-wilmer** [comment]
as if you could somehow have uniqueness without distinctivness

**Comment by cy** [comment]
I have no idea, I think we left it out originally and now there's a ticket about it. Anyway I'll ask bessie.

**Comment by cy** [comment]
she says go with unique. updated

**Pull request merged**
