### PR TITLE
🐛 PRTL-999 Entity page charts and tables should update when changing projects without leaving container

### PR DESCRIPTION
**Pull request by cheapsteak**
https://jira.opensciencedatacloud.org/browse/PRTL-999

### CODE REVIEW

**Comment by alex-wilmer** [comment]
death to `this` ❗️ 🤘

**Comment by shanewilson** [comment]
> force push part 1

are you trying to kick travis?

**Comment by cheapsteak** [comment]
deploy bot

**Comment by shanewilson** [comment]
ok deploybot is the end result of a successful travis build - so you can just re run the test in travis:

https://travis-ci.org/NCI-GDC/portal-ui/builds/219851718

button on the right can cancel/restart build

**Comment by cheapsteak** [comment]
Ahhhhh, great to know 👍

**Pull request merged**
