### PR TITLE
:sparkles: case entity to react

### PR DESCRIPTION
**Pull request by alex-wilmer**
just the beginning

### CODE REVIEW

**Comment by shanewilson** [comment]
is this a wip?

**Comment by alex-wilmer** [comment]
yeah working on it now

**Comment by alex-wilmer** [comment]
@NCI-GDC/oicrdevs rdy for review .. going to need to touch some stuff up, but this lays much of the groundwork down.

**Comment by alex-wilmer** [comment]
will break into smaller pieces

**Pull request closed without merging**
