### PR TITLE
🔥 PRTL-1358 remove ssmsBarChart

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
Not a usual removal case. I think it's worth keeping the code here, but don't render the component

**Comment by shanewilson** [comment]
so this is just removing the chart and then there is another ticket for adding the spark line?

**Comment by alex-wilmer** [comment]
that's my plan. should those go together?

**Comment by alex-wilmer** [comment]
I don't think there was a ticket for sparkline

**Comment by shanewilson** [comment]
no that's fine - just being clear

**Comment by shanewilson** [comment]
1352 has the screenshot you made

**Pull request merged**
