### PR TITLE
:sparkles: PRTL-1387 project bar axis toggle units

### PR DESCRIPTION
**Pull request by cy**
screen shot 2017-07-06 at 4 37 38 pm

### CODE REVIEW

**Comment by Jephuff** [comment]
Radio buttons seem to be getting cut off
image

**Comment by cy** [comment]
my eyes are bad! 🙈 Think i fixed it
screen shot 2017-07-07 at 2 21 03 pm

**Comment by shanewilson** [comment]
the titles on that chart seems oddly centred. Like too far left.

**Comment by cy** [comment]
you mean the radios or the 'Top Mutated Cancer Genes in Selected Projects'

**Comment by cy** [comment]
screen shot 2017-07-07 at 2 44 42 pm
?

**Comment by shanewilson** [comment]
yes that is better

**Pull request merged**
