### PR TITLE
🐛 PRTL-742 make primary site show up in facet sidebar

### PR DESCRIPTION
**Pull request by cheapsteak**
image

cases.project.primary_site -> cases.primary_site

Allow future field migrations to be specified without having to manually modify the generated files

@NCI-GDC/oicrdevs ready for review

### CODE REVIEW

**Comment by shanewilson** [comment]
can do this with GraphQL:

```
query Queries {
  __type(name: "CaseAggregations"){
    name
    fields {
      name
      description
      isDeprecated
      deprecationReason
    }
  }
}
```

**Comment by shanewilson** [comment]
@cheapsteak how much work to use graphql so you don't need that migration function

**Comment by cheapsteak** [comment]
Depends on how different the graphql data is from the mapping endpoint.
I'm also not sure where to ask for the data
If someone can figure out the graphql query to get the full results (all
the data that the mapping endpoint returns) then probably less than an hour

**Comment by shanewilson** [comment]
what is missing in the query I posted?

**Comment by shanewilson** [comment]
Oh wait you are on vacation right?

**Comment by cheapsteak** [comment]
Ah didn't see your query
Yup, New Orleans, back Friday :)

**Comment by cheapsteak** [comment]
@shanewilson That query doesn't seem to return `type`, which I need [here](https://github.com/NCI-GDC/portal-ui/blob/095c36c87e6ba5f28635c51239568299f1c865df/modules/node_modules/%40ncigdc/utils/generated-relay-query-parts/generate-script.js#L19-L40) to figure out what subfields to ask for. (It does seem to have a `type` but does not contain the same data)

**Comment by shanewilson** [comment]
what do you mean type?

**Comment by cheapsteak** [comment]
The `type`s that are returned here
https://gdc-api.nci.nih.gov/gql/_mapping
`id`/`string`/`long`

**Comment by shanewilson** [comment]
```
        {
          "deprecationReason": null,
          "description": null,
          "isDeprecated": false,
          "name": "demographic__year_of_death",
          "type": {
            "description": null,
            "kind": "OBJECT",
            "name": "Stats"
          }
        },
        {
          "deprecationReason": null,
          "description": null,
          "isDeprecated": false,
          "name": "state",
          "type": {
            "description": null,
            "kind": "OBJECT",
            "name": "Aggregations"
          }
        },
```

stats is range facet, Agg is term facet

**Comment by cheapsteak** [comment]
Continued here:
https://github.com/NCI-GDC/portal-ui/pull/1358
Using graphql to generate fragments

**Comment by cheapsteak** [comment]
DO NOT OPEN THAT EMAIL
I was just phished
---------- Forwarded message ----------
From: <cheapsteak@gmail.com>
Date: Wed, May 3, 2017 at 3:14 PM
Subject: Chang Wang has shared a document on Google Docs with you
To: hhhhhhhhhhhhhhhh@mailinator.com


Chang Wang has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=187102321219-1cb4b2gdr0bqv5u5n35vi1hecjcp1sjg.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.download%2Fg.php&customparam=customparam>

**Pull request closed without merging**
