### PR TITLE
feat(file): [PRTL-20] adds index file table

### PR DESCRIPTION
**Pull request by shanewilson**
Closes #PRTL-20

### CODE REVIEW

**Comment by shanewilson** [comment]
@cy should I use the `tablesToDisplay` thing? I wasn't really sure what that did.

**Comment by cy** [comment]
is the index file table going to be shown regardless of data_category? then you don't.

**Comment by shanewilson** [comment]
it will always be shown

**Comment by cy** [comment]
looked at the spec, if you scroll over horizontally it says
screen shot 2016-10-17 at 3 31 27 pm but it's based on data_format & data_type so use ng-if here https://github.com/NCI-GDC/portal-ui/pull/1092/files#diff-3acfaf0591334ca8b64227bfc57a39d5R494 and rename `tablesToDisplay` to `tablesToDisplayByCategory`?

**Pull request closed without merging**
