### PR TITLE
Add Explore links

### PR DESCRIPTION
**Pull request by Jephuff**
~wip~
replaces https://github.com/NCI-GDC/portal-ui/pull/1497
Links are disabled, to enable merge https://github.com/NCI-GDC/portal-ui/pull/1567

### CODE REVIEW

**Comment by alex-wilmer** [comment]
solid! so can this be merged in to relay?

**Comment by Jephuff** [comment]
Thats the goal! I'm just going to go through the original ticket and make sure I didn't lose anything.

**Comment by alex-wilmer** [comment]
fantastic. I can look at it again when you're done, but lgtm from what you have now

**Comment by Jephuff** [comment]
@alex-wilmer alright, I think it's good for testing (to test the links you can look at https://github.com/NCI-GDC/portal-ui/pull/1567)
@cheapsteak maybe you should take a look to? More eyes is probably good, there were a lot of conflicts :)

**Comment by alex-wilmer** [comment]
there were a few commits on the demo branch that i'll cherry pick into here as well

**Pull request merged**
