### PR TITLE
🐛 guard on null summary.file_count case index

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by cy** [comment]
but it crashes the whole page, showing 0 still shows the data issue. Maybe show 'null'?

**Comment by shanewilson** [comment]
I don't want to merge this because I'm concern the issue will just be ignored with people thinking it was just a UI issue - when I get confirmation it is being worked on I guess we can merge it

**Comment by alex-wilmer** [comment]
sure you want to merge this?

**Comment by shanewilson** [comment]
I don't think it matters - either way - should never be an issue but I don't think it causes any problems.

**Pull request merged**
