### PR TITLE
feat(facets): PRTL-21 term value search if n >= 20

### PR DESCRIPTION
**Pull request by cy**
Closes #21

todo:
- [x] toggle w/ magnify glass

### CODE REVIEW

**Comment by cy** [comment]
screen shot 2016-07-14 at 12 54 36 pm

**Comment by alex-wilmer** [comment]
This is cool. 

I added my comments in PR form.

**Comment by shanewilson** [comment]
would it be hard to have the list expand as soon as someone starts searching?

**Comment by cy** [comment]
expand as in the 'more...' is activated?

**Comment by shanewilson** [comment]
yes

**Comment by cy** [comment]
done, but is this crazy https://github.com/NCI-GDC/portal-ui/pull/1035/commits/6b09e3100407474be76429b85c47efacad175c83#diff-c0fe47fd4b17ef491102791162a6f683R93 toggle is expecting a mouse event to be sent in

**Comment by shanewilson** [comment]
that is crazy - lets not bother. you can revert that.

**Comment by cy** [comment]
reverted

**Pull request merged**
