### PR TITLE
🔧 prettier -> trailingComma: all, singleQuote: true

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
Just throwing this out there, but I think single quotes would be nice too. That's what we've had since as long as I've been here and I always type singles (except for when I always type backticks, but y'know)

**Comment by cy** [comment]
+1 single quotes, y`know

**Comment by shanewilson** [comment]
we can do this after the code freeze wednesday release thing

**Comment by shanewilson** [comment]
also you guys should pick out all the changes you want now cause we really shouldn't do this sort of thing very often/ever again

**Comment by alex-wilmer** [comment]
Those are the only two I care about.

**Comment by cheapsteak** [comment]
+1000 (merge conflict aside)

**Comment by alex-wilmer** [comment]
https://github.com/NCI-GDC/portal-ui/commit/afd19d94fa89ae17de0537b760ebe930cbd7a15f

**Pull request closed without merging**
