### PR TITLE
fix(files): PRTL-282 close bam modal on dl

### PR DESCRIPTION
**Pull request by alex-wilmer**
Closes #PRTL-51

### CODE REVIEW

**Comment by alex-wilmer** [comment]
@shanewilson @cy

**Comment by shanewilson** [comment]
should be https://jira.opensciencedatacloud.org/browse/PRTL-282 not PRTL-51

**Comment by seancannata** [comment]
@shanewilson Can you clarify what you mean by that last comment?

**Comment by alex-wilmer** [comment]
@seancannata he just meant to change the ticket number in the commit message, which I did.

**Pull request merged**
