### PR TITLE
🐛 move polyfills back for IE11

### PR DESCRIPTION
**Pull request by Jephuff**
~Move this to the top when we remove hot reloading, looks like I was wrong and it still needs to be after react. (waiting to test on collab)~
That ~was~ wasn't it

### CODE REVIEW

**Comment by Jephuff** [comment]
It wasn't it... but I did write `was it`. Sorry!

**Comment by cy** [comment]
i'm so confused lol

**Comment by cy** [comment]
but i did manage to get it to work in ie11 without it

**Comment by Jephuff** [comment]
yeah i'm just pushing it for the record( and so I can test :D ) :) 
Does merge maintain order?

**Pull request closed without merging**
