### PR TITLE
Feat/suggestion facet

### PR DESCRIPTION
**Pull request by cy**
screen shot 2017-01-30 at 3 11 56 pm
requires https://github.com/NCI-GDC/gdcapi/pull/688

### CODE REVIEW

**Comment by cy** [comment]
@NCI-GDC/oicrdevs this is ready for review along with https://github.com/NCI-GDC/gdcapi/pull/688

like mentioned in standup, due to index issues only works with exact matches - also ssm_id doesn't return anything even with exact match :( But the UI is there...

**Comment by alex-wilmer** [comment]
👍

**Comment by cy** [comment]
screen shot 2017-02-07 at 1 02 11 pm

**Comment by alex-wilmer** [comment]
nice 👍

**Pull request merged**
