### PR TITLE
update model

### PR DESCRIPTION
**Pull request by shanewilson**
- [ ] genes.case and cases.gene fields are being pruned:
- [x] Removing cases.files.cases double nesting:

<details>

```
-- GraphQL Validation Error -- FrequentlyMutatedGenesChart --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesChart.js
Error: Cannot query field "case" on type "Gene". Did you mean "name"?
Source:
>
>                 case {
>                 ^^^

-- GraphQL Validation Error -- FrequentlyMutatedGenesTable --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/FrequentlyMutatedGenesTable.js
Error: Cannot query field "case" on type "Gene". Did you mean "name"?
Source:
>
>                 case {
>                 ^^^

-- GraphQL Validation Error -- ProjectsCharts --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/components/ProjectsCharts.js
Error: Cannot query field "case" on type "Gene". Did you mean "name"?
Source:
>
>                 filteredCases: case {
>                 ^^^

-- GraphQL Validation Error -- ProjectsCharts --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/components/ProjectsCharts.js
Error: Cannot query field "case" on type "Gene". Did you mean "name"?
Source:
>
>                 allCases: case {
>                 ^^^

-- GraphQL Validation Error -- FilePage --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/FilePage.js
Error: Cannot query field "cases" on type "OutputFile". Did you mean "access"?
Source:
>
>                         cases {
>                         ^^^

-- GraphQL Validation Error -- CasePage --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/CasePage.js
Error: Cannot query field "cases" on type "CaseFile". Did you mean "access"?
Source:
>
>                 cases {
>                 ^^^

-- GraphQL Validation Error -- CaseTr --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/CaseTr.js
Error: Cannot query field "cases" on type "CaseFile". Did you mean "access"?
Source:
>
>                 cases {
>                 ^^^
```
</details>

### CODE REVIEW

**Comment by shanewilson** [comment]
```
-- GraphQL Validation Error -- FilePage --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/FilePage.js
Error: Cannot query field "cases" on type "OutputFile". Did you mean "access"?
Source:
>
>                         cases {
>                         ^^^

-- GraphQL Validation Error -- CaseTr --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/CaseTr.js
Error: Cannot query field "cases" on type "CaseFile". Did you mean "access"?
Source:
>
>                 cases {
>                 ^^^

-- GraphQL Validation Error -- CaseTr --

File:  /Users/swilson/Documents/Development/gdc/portal-ui/modules/node_modules/@ncigdc/containers/CaseTr.js
Error: Cannot query field "cases" on type "CaseFile". Did you mean "access"?
Source:
>
>                 cases {
>                 ^^^
```

**Comment by shanewilson** [comment]
https://github.com/NCI-GDC/gdcapi/pull/767

**Comment by shanewilson** [comment]
could someone take a look at the effort to fix those relay errors? looks like we made those queries for adding files to the cart. 

@cy @cheapsteak @alex-wilmer @Jephuff

**Comment by alex-wilmer** [comment]
should be trivial enough. it's only for getting project info. I'll make a ticket (2sp?)

**Pull request merged**
