### PR TITLE
✨ [PRTL-1639] link case counts in cohort comp

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by Jephuff** [comment]
These should have links as well right? 
image

**Comment by alex-wilmer** [comment]
yup, sorry didn't put this one up for review yet

**Comment by Jephuff** [comment]
ahh alright, I saw it in the implementation complete column so I thought I'd go for it :D I will wait :)

**Comment by alex-wilmer** [comment]
ok got this working now. (like icgc has it)

**Pull request merged**
