### PR TITLE
:bug: PRTL-763 fix overlap of facet reset/value search/remove buttons

### PR DESCRIPTION
**Pull request by cy**
screen shot 2017-03-02 at 5 14 36 pm
got all three right hand side buttons to play nice. Had to move TermAggregation's showingValueSearch state (for the mag glass) to FacetWrapper.

### CODE REVIEW

**Comment by cy** [comment]
oh wait, need to do this for all facet types and the ones on Projects page and Annotations page aren't wrapped with FacetWrapper

**Comment by shanewilson** [comment]
@cheapsteak did you have comments on this?

**Comment by cheapsteak** [comment]
Nah nvm, this looks good

**Comment by cy** [comment]
@cheapsteak wanna look again before I merge cuz I pushed after you commented

**Comment by cheapsteak** [comment]
@cy Just looked it over again, looks good :)

**Pull request merged**
