### PR TITLE
✨ PRTL-1125 no results msgs

### PR DESCRIPTION
**Pull request by cheapsteak**
Added no result messages
image
image
image

### CODE REVIEW

**Comment by cy** [comment]
rebase?

**Comment by cheapsteak** [comment]
rebased :)

**Comment by cy** [comment]
this commit `de55815` is confusing, isn't it part of this pr https://github.com/NCI-GDC/portal-ui/pull/1598...but only 2 lines from it

**Comment by cheapsteak** [comment]
Not sure how to get rid of it, rebased from origin/relay

**Comment by alex-wilmer** [comment]
`git rebase --interactive @~3` and remove it?

**Pull request merged**
