### PR TITLE
:sparkles: Quicksearch

### PR DESCRIPTION
**Pull request by cheapsteak**

### CODE REVIEW

**Comment by cheapsteak** [comment]
@NCI-GDC/oicrdevs ready for review

**Comment by alex-wilmer** [comment]
I'm perfectly happy with this PR as it is. Nice work!

Later on I would like to explore different UIs for the quicksearch but I don't have any concrete ideas at the moment and it's not that important right now.

@shanewilson  ?

**Comment by cheapsteak** [comment]
Animations can be removed by reverting 62c06a9e7b9caa461ef421283843f7fd49aed429
image

**Comment by alex-wilmer** [comment]
https://github.com/NCI-GDC/portal-ui/commit/f68b293fb582fe219c36e9eda585713736ad257f

**Pull request closed without merging**
