### PR TITLE
Feat/989 repo pie charts

### PR DESCRIPTION
**Pull request by cy**
screen shot 2017-05-01 at 3 30 36 pm
screen shot 2017-05-01 at 3 30 48 pm
but waiting for @phuongmy to confirm if project/primary_site pies can be left off files tab because they are already on cases tab

### CODE REVIEW

**Comment by shanewilson** [comment]
> project/primary_site

the ones on case should count cases and the ones on files should count files

**Comment by cy** [comment]
my mistake, adding them now

**Comment by cy** [comment]
screen shot 2017-05-02 at 3 39 15 pm
@shanewilson added those

ready for review

**Comment by shanewilson** [comment]
27207 vs 8648?

**Comment by cy** [comment]
screen shot 2017-05-02 at 3 42 03 pm
took the screenshot before the query came back

**Pull request merged**
