### PR TITLE
name as survival analysis

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by cheapsteak** [comment]
Is this just for the demo?  
I'm not sure about the UX on this  
The behaviour seems rather unintuitive, people would not expect clicking the name would be related to the graph (name is an identifier, would expect the same behaviour as clicking on ID)

**Comment by alex-wilmer** [comment]
> Is this just for the demo?

yes

**Comment by shanewilson** [comment]
who asked for this change?

**Comment by shanewilson** [comment]
oh its an attempt to prevent scrolling - ok

**Pull request closed without merging**
