### PR TITLE
[wip] 1219 mutations count

### PR DESCRIPTION
**Pull request by cy**
maybe a fix - actually couldn't reproduce before. Opening pr for BA to test.

### CODE REVIEW

**Comment by alex-wilmer** [comment]
interesting. why was createElement used there? I think those two things are equivalent. also I'm thinking that mutations count should be its own renderer too which would surely fix this in case this doesn't

**Comment by cy** [comment]
yeah, I was testing out createElement instead of jsx one time and committed it accidentally. The thing I was thinking might make a difference was passing in query.fmgTable_filters as well. But it does look like defaultFilters is the thing used on the GenesTab table.

**Comment by cy** [comment]
and Bessie's saying it was the CaseTable after all :x lol

**Comment by alex-wilmer** [comment]
mmm can we leave this? I'm trying to remove all the force fetching. or maybe you want to test making mutations count into its own renderer like one of these: https://github.com/NCI-GDC/portal-ui/tree/0508f71789ef856f14205185e83a4dd5914776e0/modules/node_modules/%40ncigdc/modern_components

**Comment by cy** [comment]
relayyyyyyy. fine

**Comment by cy** [comment]
to be replaced

**Pull request closed without merging**
