### PR TITLE
Lolliplot container

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by Jephuff** [comment]
@alex-wilmer is this ready for review?

**Comment by alex-wilmer** [comment]
This is waiting for a data improvement. Also to note it's currently just the gene page, though it might be worth putting it on the ssm page in a later PR. Is there another ticket waiting for this to be complete?

**Comment by Jephuff** [comment]
nope! just going through all the open PRs 👍

**Comment by alex-wilmer** [comment]
@Jephuff @NCI-GDC/oicrdevs  this is now ready for review. A small upgrade will need to be made to accomodate the mutation page (basically.. check if gene has been populated from the parent, if not set a relay variable to fetch the gene) but I think that's worth doing in another PR that containerizes the mutation page.

**Pull request merged**
