### PR TITLE
Fix/lolliplot

### PR DESCRIPTION
**Pull request by alex-wilmer**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
using window seems kind of hacky, but it might actually be useful here. or at least something that's going to hold the data and update it without causing any re-renders.

**Comment by Jephuff** [comment]
Hmmm, the window thing seems like it would be error prone(render order becomes very important). It would also mean we have to make sure only 1 lolliplot is rendered at the same time.
Might be better to pass it through LolliplotWrappers state, looks like setState is already passed in.
to avoid renders you could make LolliplotWrapper a class and store the data there, and pass a function to `DownloadVisualizationButton` for the data :)

**Comment by cy** [comment]
I get this error on this branch but not on master:
```
Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Object.escape (:3000/static/js/bundle.js:91052)
    at getComponentKey (:3000/static/js/bundle.js:121530)
    at traverseAllChildrenImpl (:3000/static/js/bundle.js:121571)
    at traverseAllChildren (:3000/static/js/bundle.js:121651)
    at flattenChildren (:3000/static/js/bundle.js:317437)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314810)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at Object.updateChildren (:3000/static/js/bundle.js:309886)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314814)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at Object.updateChildren (:3000/static/js/bundle.js:309886)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314814)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at Object.updateChildren (:3000/static/js/bundle.js:309886)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314814)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310736)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at Object.updateChildren (:3000/static/js/bundle.js:309886)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314814)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
:3000/static/js/bundle.js:61025 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (:3000/static/js/bundle.js:61025)
    at ReactCompositeComponentWrapper.getHostNode (:3000/static/js/bundle.js:310366)
    at Object.getHostNode (:3000/static/js/bundle.js:61025)
    at ReactCompositeComponentWrapper.getHostNode (:3000/static/js/bundle.js:310366)
    at Object.getHostNode (:3000/static/js/bundle.js:61025)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310738)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at Object.updateChildren (:3000/static/js/bundle.js:309886)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314814)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310736)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310736)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310736)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310736)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at ReactCompositeComponentWrapper._updateRenderedComponent (:3000/static/js/bundle.js:310736)
    at ReactCompositeComponentWrapper._performComponentUpdate (:3000/static/js/bundle.js:310706)
    at ReactCompositeComponentWrapper.updateComponent (:3000/static/js/bundle.js:310627)
    at ReactCompositeComponentWrapper.receiveComponent (:3000/static/js/bundle.js:310529)
    at Object.receiveComponent (:3000/static/js/bundle.js:61087)
    at Object.updateChildren (:3000/static/js/bundle.js:309886)
    at ReactDOMComponent._reconcilerUpdateChildren (:3000/static/js/bundle.js:314814)
    at ReactDOMComponent._updateChildren (:3000/static/js/bundle.js:314918)
    at ReactDOMComponent.updateChildren (:3000/static/js/bundle.js:314905)
    at ReactDOMComponent._updateDOMChildren (:3000/static/js/bundle.js:311951)
    at ReactDOMComponent.updateComponent (:3000/static/js/bundle.js:311769)
    at ReactDOMComponent.receiveComponent (:3000/static/js/bundle.js:311731)
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:346)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:299)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:936)
    at ReactDOMComponent.updateComponent (ReactDOMComponent.js:754)
    at ReactDOMComponent.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (ReactCompositeComponent.js:561)
    at Object.performUpdateIfNecessary (ReactReconciler.js:157)
    at runBatchedUpdates (ReactUpdates.js:150)
    at ReactReconcileTransaction.perform (Transaction.js:140)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:140)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
    at Object.flushBatchedUpdates (ReactUpdates.js:172)
    at ReactDefaultBatchingStrategyTransaction.closeAll (Transaction.js:206)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:153)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
    at Object.batchedUpdates (ReactUpdates.js:97)
    at dispatchEvent (ReactEventListener.js:147)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:63
_updateChildren @ ReactMultiChild.js:346
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:157
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:63)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:346)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:299)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:936)
    at ReactDOMComponent.updateComponent (ReactDOMComponent.js:754)
    at ReactDOMComponent.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (ReactCompositeComponent.js:561)
    at Object.performUpdateIfNecessary (ReactReconciler.js:157)
    at runBatchedUpdates (ReactUpdates.js:150)
    at ReactReconcileTransaction.perform (Transaction.js:140)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:140)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
    at Object.flushBatchedUpdates (ReactUpdates.js:172)
    at ReactDefaultBatchingStrategyTransaction.closeAll (Transaction.js:206)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:153)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
    at Object.batchedUpdates (ReactUpdates.js:97)
    at dispatchEvent (ReactEventListener.js:147)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:63
_updateChildren @ ReactMultiChild.js:346
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:157
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
```

**Comment by alex-wilmer** [comment]
doh >< was afraid of that. that's why I had `window` the first time. 🤔

**Comment by alex-wilmer** [comment]
@cy ok I think the last commit fixed that

**Pull request merged**
