### PR TITLE
✨ [PRTL-703] custom facets modal : allow filtering out facets that are not useful

### PR DESCRIPTION
**Pull request by cheapsteak**
@shanewilson You were right, it did turn out to be simpler to reuse stuff from CaseAggreagations and FileAggregations :)

### CODE REVIEW

**Comment by cheapsteak** [comment]
@cy great ideas
Implemented and pushed!

**Comment by cy** [comment]
doesn't seem to happen on the relay branch, but flipping between the 'Case' and 'File' facet tabs causes some of the custom facets to all become 'No data for this field' when flipping back.
screen shot 2017-03-01 at 3 16 42 pm
screen shot 2017-03-01 at 3 16 55 pm

**Comment by cheapsteak** [comment]
@cy great catch, fixed up TermAggregations to reactively determine what its filtered buckets are. It used to set the value in the instant of `componentDidMount` and when a keyword is clicked, now it computes each time `buckets` or `filters` changes.

ready for re review

**Comment by cheapsteak** [comment]
Sounds good!

**Pull request merged**
