### PR TITLE
✨ retry middleware that takes the first successfull query

### PR DESCRIPTION
**Pull request by Jephuff**
Took a stab at making the retry middleware take the first successful response, seems to work.
Needs more testing/refactoring but thought I would be it here if anyone wants to take a look.

### CODE REVIEW

**Comment by shanewilson** [comment]
what did you change?

**Comment by Jephuff** [comment]
mainly timeouts don't reject the promise and creates a new promise thats put in an array with a promise.race

**Comment by shanewilson** [comment]
can you rebase?

**Comment by shanewilson** [comment]
what page are you testing to see reduced requests?

**Comment by Jephuff** [comment]
connected to UAT on the exploration page it would have multiple requests, it's the only consistent case I've found

**Comment by Jephuff** [comment]
Had to use this branch to be able to click the facets with data checkbox, probably worth looking at merging this after today.

**Comment by shanewilson** [comment]
what happened?

**Comment by Jephuff** [comment]
The requests time out and max retries fire. With this retries fire until the first request returns. I guess we could also increase timeout.

**Comment by shanewilson** [comment]
how did you reproduce this? it would be nice to see it in action

**Comment by Jephuff** [comment]
hmmm, now it's loading quite quickly, I wonder if something was happening to the UAT server.
all I did before, was running api locally point to UAT go to explore page and 
`Add a Case Filter` -> `Only show fields with values`
I'll keep my eye out for another case

**Pull request merged**
