### PR TITLE
fix(tree): 2572 expand first entity with children

### PR DESCRIPTION
**Pull request by alex-wilmer**
TODO:
- [x] group entities with fake parents
- [x] add comments to BiospecimenService
- [x] more test cases
- [x] use stitching algo instead of grouping paths

### CODE REVIEW

**Comment by shanewilson** [comment]
does this still have edge cases?

**Comment by alex-wilmer** [comment]
Hmm yes most likely but not for any foreseeable data model we might run into.. I can imagine crazier bio trees with more gaps between actual nodes and placeholders that would make the UI slightly off, but not broken or unusable. I think the code works for what we have + the tests match that.

**Comment by shanewilson** [comment]
👍

**Comment by alex-wilmer** [comment]
@cy @ithinkicancode ? To test this in the app you can visit http://localhost:3000/cases/001c294c-5ae8-55cd-bf07-88112e9b117b and notice that its possible to expand aliquots whereas on develop they are not visible because they are nested under placeholder nodes which are not visible https://gdc-portal.nci.nih.gov/cases/001c294c-5ae8-55cd-bf07-88112e9b117b

**Comment by cy** [comment]
👍

**Pull request merged**
