### PR TITLE
🛠 only commit staged changes

### PR DESCRIPTION
**Pull request by Jephuff**
Proposed change to precommit: This stashes unstaged changes and then restores them so you can do partial commits.

### CODE REVIEW

**Comment by shanewilson** [comment]
hmm - have you read through these?

https://github.com/okonet/lint-staged/issues/62
https://github.com/facebookincubator/create-react-app/pull/1759

they talk about merge conflicts coming about after the pop.

Can you setup sourcetree to use --no-verify?

**Comment by Jephuff** [comment]
I think the merge conflicts from popping would be pretty rare, and only when you are committing a file partially.
But If i'm the only one who has a workflow like this, I can just just skip the hook locally :)

**Comment by shanewilson** [comment]
well we could also just remove the hook. if everyone has auto formatting on their editors then it does nothing

**Comment by cheapsteak** [comment]
Partial commits would also be useful for me as well

Just set up format on save

**Comment by Jephuff** [comment]
Is anyone relying on the precommit to lint their files? we could leave `eslint` in so it blocks unlinted commits.

**Comment by Jephuff** [comment]
@cheapsteak no complaints from me. We could also gitignore the settings file now that we don't need to support node_modules?

**Comment by cheapsteak** [comment]
either way works for me, whatever would allow me to stop having to stash and unstash my settings between branches and pulls

**Comment by shanewilson** [comment]
I would prefer we go with simple and not in anyones way. It looks like the easiest solution is to remove lint-staged. I'm fine with this since I get no benefit from it anyway - it was mostly because I thought @Jephuff didn't want to use auto-format on his editor.

**Pull request closed without merging**
