### PR TITLE
:bug: PRTL-917 Ssm Consequences tbl, show CollapsibleList of Transcripts

### PR DESCRIPTION
**Pull request by cy**
screen shot 2017-03-29 at 5 26 03 pm
this is ready but did I hear we're getting rid of canonical transcript? ticket says sort it to the top.

### CODE REVIEW

**Comment by cy** [comment]
screen shot 2017-03-30 at 4 00 18 pm
ready for review @NCI-GDC/oicrdevs

**Comment by cheapsteak** [comment]
http://deploybot.gdc.cheapsteak.net:33251/projects/TCGA-BRCA

image

**Comment by cheapsteak** [comment]
looks great otherwise :)

**Comment by cy** [comment]
@cheapsteak thanks fixed

**Comment by cheapsteak** [comment]
now get `theme is not defined`, also merge conflict (sorry that might be from one of my prs)

**Comment by cy** [comment]
fixeddd

**Comment by cheapsteak** [comment]
@cy yikes, looks like it's still erroring out on the project page

**Comment by cheapsteak** [comment]
Uncaught (in promise) ReferenceError: theme is not defined

**Pull request merged**
