### PR TITLE
feat(app): PRTL-13 copy to clipboard button

### PR DESCRIPTION
**Pull request by alex-wilmer**
- install clipboard & ngclipboard

Closes #PRTL-13

### CODE REVIEW

**Comment by cy** [comment]
it copies! Is the tooltip tail placement off or just my resolution?
screen shot 2016-07-20 at 4 13 03 pm

**Comment by alex-wilmer** [comment]
😠 yea it looks off..

**Comment by alex-wilmer** [comment]
@cy updated... I didn't see a preceding style that made it upside down *shrug*

**Comment by alex-wilmer** [comment]
mm I'll add the `data-` prefixes as well

**Comment by cy** [comment]
haha, you're flipping it 180 - do you see this weird moving to the left of the tail after the tooltip shows up too? Why ui-boostrap!

**Comment by cy** [comment]
oh how about just using `tooltip-placement="top"`, ui-bootstrap seems happy with that
screen shot 2016-07-27 at 10 40 39 am

**Comment by alex-wilmer** [comment]
hah okay

**Comment by alex-wilmer** [comment]
ui-bootstrap no more!

**Comment by cy** [comment]
👍

**Comment by shanewilson** [comment]
@cy can you update with review feature

**Comment by shanewilson** [comment]
Does this require a lot of testing? can we just close it and add it to the React version later?

**Comment by alex-wilmer** [comment]
> Does this require a lot of testing?

Not really, should be fine to merge.

> can we just close it and add it to the React version later?

I'm indifferent on that point... no one has made a big fuss about not having this.

**Comment by shanewilson** [comment]
ok can you set the ticket back to Rdy for Impl? and move it to the backlog if it isn't already.

**Pull request closed without merging**
