### PR TITLE
🐛 use urlJoin for concating API and GDC_AUTH

### PR DESCRIPTION
**Pull request by Jephuff**

### CODE REVIEW

**Comment by cheapsteak** [comment]
As discussed with Jeffrey, 
Love this PR  
Needs a regression test though  
Today isn't a good day to risk breaking things on any page that makes a data request  

Let's keep this open until we have capacity to test

**Comment by shanewilson** [comment]
I'm assuming we don't need this anymore?

**Comment by Jephuff** [comment]
We don't need it, but I think it's still a good idea. 
if we use urlJoin instead of concat then we don't have to worry if the variable ends with a slash or not :)

**Comment by shanewilson** [comment]
okay sounds good.
how come url-join was already in pkg.json?

**Comment by Jephuff** [comment]
this pull request use to be huge, so I started updating when I was already in a file. To avoid unnecessary bugs.

**Comment by shanewilson** [comment]
status?

**Comment by Jephuff** [comment]
rebased, site still works :)

**Pull request merged**
