### PR TITLE
🐛 PRTL-1109 facet shows no data

### PR DESCRIPTION
**Pull request by cheapsteak**
Fixes problem with custom facets showing no data after being selected

### CODE REVIEW

**Comment by shanewilson** [comment]
at some point it might be worth looking into using `facets` instead of `aggregations`

**Comment by cheapsteak** [comment]
Do have documentation & sample queries? How much effort would it be?

**Comment by cheapsteak** [comment]
Wonder if we could do it a piece at a time or would everything need to migrate over at once?

**Comment by shanewilson** [comment]
they both exists right now - just need to use it where it makes sense. the query would be:

```
query Q($facets: JSONString, $filters: FiltersArgument) {
  repository {
    cases {
      facets(facets: $facets, filters: $filters)
    }
  }
}

variables: {
 facets: ['primary_site', 'project.name'],
 filters: { ...blah...}
}
```

**Comment by shanewilson** [comment]
should we merge this is a fix until we move the `facets`?

**Comment by shanewilson** [comment]
https://jira.opensciencedatacloud.org/browse/PRTL-1109 says it is merged?

**Comment by cheapsteak** [comment]
Yeah let's merge, it's not as good as using facets but net positive on bug reduction. 

I merged that ticket when I merged the ticket that I thought fixed it but turns out it wasn't really fixed

**Pull request merged**
